'use strict';

const EXPECTED_API_VERSION = 49;

const STATUS = {
  OK: 0,
  INVALID_CONFIG: 1,
  INVALID_QUERY: 2,
  KERNEL_LOAD: 3,
  TIME_CONVERSION: 4,
  UNSUPPORTED_QUERY: 5,
  EPOCH_OUT_OF_RANGE: 6,
  NULL_POINTER: 7,
  EOP_LOAD: 8,
  EOP_OUT_OF_RANGE: 9,
  INVALID_LOCATION: 10,
  NO_CONVERGENCE: 11,
  INVALID_SEARCH_CONFIG: 12,
  INVALID_INPUT: 13,
  INTERNAL: 255,
};

const STATUS_NAME = new Map(
  Object.entries(STATUS).map(([k, v]) => [v, k]),
);

const QUERY_TIME = {
  JD_TDB: 0,
  UTC: 1,
};

const QUERY_OUTPUT = {
  CARTESIAN: 0,
  SPHERICAL: 1,
  BOTH: 2,
};

const TIME_POLICY = {
  STRICT_LSK: 0,
  HYBRID_DELTA_T: 1,
};

const DELTA_T_MODEL = {
  LEGACY_ESPENAK_MEEUS_2006: 0,
  SMH2016_WITH_PRE720_QUADRATIC: 1,
};

const FUTURE_DELTA_T_TRANSITION = {
  LEGACY_TT_UTC_BLEND: 0,
  BRIDGE_FROM_MODERN_ENDPOINT: 1,
};

const SMH_FUTURE_FAMILY = {
  ADDENDUM_2020_PIECEWISE: 0,
  CONSTANT_C_MINUS20: 1,
  CONSTANT_C_MINUS17P52: 2,
  CONSTANT_C_MINUS15P32: 3,
  STEPHENSON_1997: 4,
  STEPHENSON_2016: 5,
};

const TT_UTC_SOURCE = {
  LSK_DELTA_AT: 0,
  DELTA_T_MODEL: 1,
};

const TIME_WARNING = {
  LSK_FUTURE_FROZEN: 0,
  LSK_PRE_RANGE_FALLBACK: 1,
  EOP_FUTURE_FROZEN: 2,
  EOP_PRE_RANGE_FALLBACK: 3,
  DELTA_T_MODEL_USED: 4,
};

function statusName(code) {
  return STATUS_NAME.get(code) || `UNKNOWN_${code}`;
}

module.exports = {
  EXPECTED_API_VERSION,
  DELTA_T_MODEL,
  FUTURE_DELTA_T_TRANSITION,
  QUERY_OUTPUT,
  QUERY_TIME,
  SMH_FUTURE_FAMILY,
  STATUS,
  TIME_POLICY,
  TIME_WARNING,
  TT_UTC_SOURCE,
  statusName,
};
